#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = ooo_micro_arch

SRC_FILES = ooo-micro-arch.c

MODULE_CFLAGS = -DTARGET_SPARC_V9

SIMICS_API=2.0

include $(MODULE_MAKEFILE)
