
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = 'W#\xc9B8\xd2\x91/\xc6\x98T\xda\xc4!75'

_lr_action_items = {'COMMENT':([0,],[1,]),'LPAR':([17,18,23,32,35,37,],[18,18,18,18,18,18,]),'LBRAC':([37,23,17,10,32,18,35,],[23,23,23,11,23,23,23,]),'RAWEND':([39,],[42,]),'RBRAC':([22,41,0,20,23,35,31,18,33,36,19,12,15,30,13,42,28,11,40,],[-8,-18,-20,-7,-20,-20,-19,-20,-11,-15,-9,14,-5,-17,-6,-10,36,-20,-16,]),'OBJECT':([11,2,0,6,4,23,35,14,18,],[-20,7,-20,-2,-3,-20,-20,-4,-20,]),'$':([2,23,5,4,14,18,0,3,35,6,11,],[-1,-20,-21,-3,-4,-20,-20,0,-20,-2,-20,]),'RPAR':([26,36,22,24,35,0,23,38,18,19,33,42,25,11,],[-14,-15,-8,-13,-20,-20,-20,-12,-20,-9,-11,-10,33,-20,]),'COMMA':([11,36,26,38,23,25,35,19,40,18,28,22,33,24,41,31,0,42,30,],[-20,-15,-14,-12,-20,32,-20,-9,-16,-20,35,-8,-11,-13,-18,-19,-20,-10,-17,]),'LINECOMMENT':([1,],[5,]),'COLON':([22,33,36,42,29,16,19,],[-8,-11,-15,-10,37,17,-9,]),'RAWSTART':([18,37,17,35,23,32,],[21,21,21,21,21,21,]),'TYPE':([8,],[9,]),'ID':([42,22,35,7,13,23,17,9,19,33,15,12,11,21,36,32,37,18,20,34,0,],[-10,-8,22,8,-6,22,22,10,-9,-11,-5,16,-20,27,-15,22,22,22,-7,39,-20,]),'STRING':([18,32,35,17,37,23,27,],[19,19,19,19,19,19,34,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'pairs':([23,],[28,]),'attribute':([12,],[15,]),'object':([2,],[6,]),'value':([17,18,37,23,32,35,],[20,24,41,29,38,29,]),'objects':([0,],[2,]),'valuelist':([18,],[25,]),'pair':([35,23,],[40,30,]),'attributes':([11,],[12,]),'configuration':([0,],[3,]),'empty':([18,11,23,35,0,],[26,13,31,31,4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('configuration',1,'p_configuration','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',72),
  ('objects',2,'p_objects','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',76),
  ('objects',1,'p_objects_empty','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',80),
  ('object',7,'p_object','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',84),
  ('attributes',2,'p_attributes','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',88),
  ('attributes',1,'p_attributes_empty','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',92),
  ('attribute',3,'p_attribute','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',96),
  ('value',1,'p_value_id','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',100),
  ('value',1,'p_value_string','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',104),
  ('value',5,'p_value_raw','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',108),
  ('value',3,'p_value_list','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',112),
  ('valuelist',3,'p_valuelist','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',116),
  ('valuelist',1,'p_valuelist_value','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',120),
  ('valuelist',1,'p_valuelist_empty','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',124),
  ('value',3,'p_value_dict','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',128),
  ('pairs',3,'p_pairs','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',132),
  ('pairs',1,'p_pairs_pair','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',137),
  ('pair',3,'p_pair','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',141),
  ('pair',1,'p_pair_empty','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',145),
  ('empty',0,'p_empty','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',149),
  ('configuration',2,'p_dummy','/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/scripts/checkpoint-merge.py',154),
]
