#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = local-space-mapper

SRC_FILES= local-space-mapper.c

include $(MODULE_MAKEFILE)
