#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

SRC_FILES = sample-user-decoder.c

include $(MODULE_MAKEFILE)
