#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = trans-staller

SRC_FILES = staller.c

include $(MODULE_MAKEFILE)
