#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = consistency-controller

SRC_FILES = consistency-controller.c

include $(MODULE_MAKEFILE)
