#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = AM79C960-dml

SRC_FILES=
DML_FILES= AM79C960.dml

MODULE_CFLAGS = -I$(SIMICS_BASE)/src/devices/common
DMLC_FLAGS = -m

include $(MODULE_MAKEFILE)
