#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

SRC_FILES = sample_device_python.py

include $(MODULE_MAKEFILE)
