#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = sample_device_dml

SRC_FILES=
DML_FILES= sample-device-dml.dml

DMLC_FLAGS = -m

include $(MODULE_MAKEFILE)
