#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = id-splitter

SRC_FILES = id-splitter.c

include $(MODULE_MAKEFILE)
