#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = x86-tlb

SRC_FILES= x86_tlb.c assoc.c hash_based.c full_table.c

include $(MODULE_MAKEFILE)
