#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

SRC_FILES = $(wildcard $(SRC_BASE)/$(TARGET)/*_components.py)

include $(MODULE_MAKEFILE)
