#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES=x86-reset-bus

SRC_FILES = x86-reset-bus.c

include $(MODULE_MAKEFILE)
