#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = sample-device

SRC_FILES= sample-device.c

include $(MODULE_MAKEFILE)
