#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

SRC_FILES = context_switcher.py

include $(MODULE_MAKEFILE)
