#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = simple-byte-dump

SRC_FILES= simple-byte-dump.c

include $(MODULE_MAKEFILE)
