#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = DS12887-dml

SRC_FILES=
DML_FILES= DS12887.dml

MODULE_CFLAGS = -I$(SIMICS_BASE)/src/devices/common
DMLC_FLAGS = -m

include $(MODULE_MAKEFILE)
