#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = AM79C973

SRC_FILES=
DML_FILES= AM79C973.dml

DMLC_FLAGS = -m

include $(MODULE_MAKEFILE)
