#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

SRC_FILES = x86_linux_process_tracker.py

include $(MODULE_MAKEFILE)
