#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

# USER-TODO: specify the class(es) implemented in this module
MODULE_CLASSES=empty-device

# USER-TODO: set file-names
SRC_FILES = empty-device.c

MODULE_CFLAGS =

EXTRA_VPATH=

include $(MODULE_MAKEFILE)
