# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the workspace setup script.

SIMICS_BASE=/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31
SIMICS_WORKSPACE=/home/jalbe/comun/gems/ws

# allow user to override HOST_TYPE
ifeq (,$(HOST_TYPE))
HOST_TYPE=$(shell $(SIMICS_BASE)/scripts/host-type.sh)
endif

ifeq (x86-win32,$(HOST_TYPE))
CYGWRAP=/export/home/jalbe/comun/gems/ws/cygwrap.exe
endif

include compiler.mk

include $(SIMICS_BASE)/config/config.mk

# Put user definitions in config-user.mk
-include config-user.mk

# Deprecated
-include Config-user.mk
