#!/bin/sh
# this file will be overwritten by the workspace setup script
SIMICS_WORKSPACE="/home/jalbe/comun/gems/ws"; export SIMICS_WORKSPACE
exec "/home/jalbe/comun/gems/simics-3.0-install/simics-3.0.31/bin/simics"  ${1+"$@"}
