# -*- makefile -*-
#
# Sample makefile for the DML device: "empty-dml-device"
# See the Simics Programming Guide for more details on what to put here.
#

MODULE_CLASSES = empty_dml_device
SRC_FILES = 
DML_FILES = empty-dml-device.dml
DMLC_FLAGS = -m

include $(MODULE_MAKEFILE)
