#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = sample_micro_arch_x86

SRC_FILES = sample-micro-arch-x86.c

include $(MODULE_MAKEFILE)
