#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = sample-memhier

SRC_FILES = sample-memhier.c

include $(MODULE_MAKEFILE)
