#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = sample-i2c-device

SRC_FILES= sample-i2c-device.c i2c-device.c

EXTRA_VPATH=$(SIMICS_BASE)/src/devices/i2c-device

include $(MODULE_MAKEFILE)
