#                                                              -*- Makefile -*-
# Copyright (c) Virtutech AB, All Rights Reserved
#
# Simics module makefile
#

MODULE_CLASSES = sample_micro_arch

SRC_FILES = sample-micro-arch.c

include $(MODULE_MAKEFILE)
